services:
  nochnaya-krone:
    build: .
    container_name: nochnaya-krone
    restart: unless-stopped
    volumes:
      - nochnaya-krone-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SESSION_SECRET=HIER_EIN_SICHERES_PASSWORT_EINSETZEN
      - DISCORD_CLIENT_ID=1477714942647079074
      - DISCORD_CLIENT_SECRET=A-mHq0cHPnOaIIh03GvCi1rebJn3ciu8
      - DISCORD_REDIRECT_URI=https://nochnaya.3r6nuss.de/auth/callback
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1479919998674665653/p6t5j7ICPOJSZxV6TOqB90V1Q-XZDJo2Y4IjT6GD3pY1ZAK2UG8T2vPsSZFiqWen-O5M
      - OCR_SERVICE_URL=http://ocr-service:8000
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=1480172872063520819
    networks:
      - nginx-proxy-manager_default

  ocr-service:
    build: ./ocr-service
    container_name: nochnaya-krone-ocr
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

volumes:
  nochnaya-krone-data:
    name: nochnaya-krone-data


networks:
  nginx-proxy-manager_default:
    external: true
